import { Bot, Box, Building2, Camera, ChevronRight, CloudLightning, Compass, GraduationCap, Map, Mountain, ScanLine, Video, Waypoints } from 'lucide-react'

const features = [{ icon: Box, title: '2D to 3D Conversion', copy: 'Transform a single 2D image into an interactive 3D representation.' }, { icon: Mountain, title: 'Height Estimation', copy: 'Estimate relative terrain elevation and depth from visual information.' }, { icon: ScanLine, title: 'Terrain Analysis', copy: 'Surface meaningful terrain insights through clear visual exploration.' }, { icon: Video, title: '3D Flythrough', copy: 'Navigate the reconstructed terrain through an immersive flythrough.' }]
const steps = ['Upload Image', 'AI Depth Analysis', 'Height Estimation', '3D Terrain Reconstruction', 'Interactive Flythrough']
const applications = [{ icon: CloudLightning, name: 'Disaster Management' }, { icon: Compass, name: 'Terrain Exploration' }, { icon: Building2, name: 'Urban Planning' }, { icon: Map, name: 'Geographic Analysis' }, { icon: Waypoints, name: 'Surveying and Mapping' }, { icon: GraduationCap, name: 'Education and Research' }]
const technology = ['Artificial Intelligence', 'Computer Vision', 'Depth Estimation', '3D Reconstruction', 'Python / FastAPI', 'React', '3D Visualization']

export default function AboutPage() {
  return <div className="information-page about-page">
    <section className="information-hero"><div className="information-grid" /><p className="eyebrow"><Bot size={14} /> ABOUT 3D DEPTHVISION</p><h2>Turning a Single 2D Image into an <em>Immersive 3D World.</em></h2><p>3D DepthVision combines AI, computer vision, depth estimation, and interactive 3D visualization to transform a single 2D image into a meaningful representation of terrain and depth.</p></section>
    <section className="vision-card"><div><p className="eyebrow">OUR VISION</p><h3>Making terrain understanding smarter, faster and more accessible.</h3></div><p>We simplify terrain analysis and visualization through AI-powered technology, helping people move from a static image to a spatial perspective that is easier to explore, explain, and act on.</p></section>
    <section><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h3>From pixels to perspective</h3></div><p>A focused workflow designed to make depth-driven terrain understanding approachable.</p></div><div className="about-feature-grid">{features.map(({ icon: Icon, title, copy }) => <article className="about-feature-card" key={title}><span><Icon size={22} /></span><h4>{title}</h4><p>{copy}</p></article>)}</div></section>
    <section className="process-section"><div className="section-heading"><div><p className="eyebrow">HOW IT WORKS</p><h3>One image. Five intelligent steps.</h3></div></div><div className="process-flow">{steps.map((step, index) => <div className="process-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < steps.length - 1 && <ChevronRight className="process-arrow" size={18} />}</div>)}</div></section>
    <section className="applications-section"><div><p className="eyebrow">WHY 3D DEPTHVISION?</p><h3>Spatial insight for decisions that matter.</h3><p>Designed as a practical demonstration of how intelligent reconstruction can support field teams, planners, researchers, and learners.</p></div><div className="application-grid">{applications.map(({ icon: Icon, name }) => <div key={name}><Icon size={18} /><span>{name}</span></div>)}</div></section>
    <section><div className="section-heading"><div><p className="eyebrow">OUR TECHNOLOGY</p><h3>Built for intelligent visualization</h3></div></div><div className="technology-list">{technology.map(item => <span key={item}>{item}</span>)}</div></section>
  </div>
}
