import { BarChart2, BookmarkPlus, CheckCircle2, Image } from 'lucide-react'

function formatSize(bytes = 0) { return !bytes ? 'Not available' : bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(2)} MB` : `${Math.round(bytes / 1024)} KB` }
function modeLabel(mode) { return mode === 'anime' ? '3D Character' : `3D ${mode?.[0]?.toUpperCase() || ''}${mode?.slice(1) || ''}` }

export default function AnalyticsPanel({ fileId, uploadedFile, depthResult, objectData, terrainData, inputAnalysis, history = [], reconstructionMode, inputViewCount = 1, onSave, canSave }) {
  if (!fileId || !uploadedFile) return <div className="state-box"><BarChart2 size={48} className="state-icon" /><h3>No project loaded</h3><p>Upload an image to view its reconstruction details and processing status.</p></div>
  const completed = Boolean(objectData || terrainData)
  const processingTime = depthResult?.processing_time_sec ? `${depthResult.processing_time_sec}s for depth inference` : 'Not completed'
  const rows = [
    ['Generated models', String(history.length)], ['Reconstruction type', modeLabel(reconstructionMode)], ['Reconstruction status', completed ? 'Completed' : depthResult ? 'Depth ready — mesh not generated' : 'Image uploaded'], ['Input quality', inputAnalysis ? `${Math.round(inputAnalysis.input_quality * 100)}% · ${inputAnalysis.input_quality_label}` : 'Pending analysis'], ['Input views', `${inputViewCount} (local mesh uses the primary image)`], ['Image dimensions', `${uploadedFile.width} × ${uploadedFile.height}px`], ['File size', formatSize(uploadedFile.size)], ['Processing time', processingTime], ['Depth model', depthResult?.model_name?.split('/').pop() || 'Not run'], ['Geometry', objectData ? 'Textured visible-surface triangle mesh' : terrainData ? `${terrainData.grid_size} × ${terrainData.grid_size} terrain grid` : 'Not generated'], ['Confidence', objectData ? `${Math.round(objectData.reconstruction_confidence * 100)}% visible-surface estimate` : terrainData ? `${Math.round((terrainData.stats?.confidence_max || 0) * 100)}% max terrain estimate` : 'Not available'], ['Created', new Date().toLocaleString()],
  ]
  return <div className="photo-details">
    <section className="card-panel"><div className="card-title"><h3><Image size={18} /> Project details</h3>{canSave && <button className="btn btn-secondary" onClick={onSave}><BookmarkPlus size={15} /> Save to History</button>}</div><p className="details-copy">Project analytics records the reconstruction inputs and outputs. It does not add files to history until a reconstruction finishes or you explicitly save it.</p><div className="photo-details-grid"><div className="details-preview"><img src={uploadedFile.localUrl} alt="Original uploaded image" /><span>Preserved original image</span></div><div className="meta-list">{rows.map(([label, value]) => <div className="meta-row" key={label}><span className="meta-label">{label}</span><span className="meta-value">{value}</span></div>)}</div></div></section>
    {depthResult && <section className="card-panel"><div className="card-title"><h3><CheckCircle2 size={18} /> Reconstruction inputs</h3><span className="title-badge">{completed ? 'COMPLETE' : 'IN PROGRESS'}</span></div><div className="img-compare"><div className="img-panel"><label>Original 2D image</label><img src={uploadedFile.localUrl} alt="Original" /></div><div className="img-panel"><label>Generated depth visualization</label><img src={depthResult.visual_depth_url} alt="Depth visualization" /></div></div></section>}
  </div>
}
