import { useMemo, useRef, useState } from 'react'
import { AlertCircle, ArrowDown, ArrowUp, CheckCircle, Plus, Replace, Trash2, UploadCloud, View } from 'lucide-react'

const ALLOWED = ['image/jpeg', 'image/png']; const MAX_MB = 10
const MODE_COPY = {
  terrain: { eyebrow: '3D TERRAIN INPUT', title: 'Upload geographic imagery', body: 'Best for landscapes, elevation, terrain, roads, fields, and geographic surfaces. Use one aerial, satellite, drone, or topographic image.', label: 'Terrain image', allowMulti: false },
  object: { eyebrow: '3D OBJECT INPUT', title: 'Upload an object from any angle', body: 'A single image is treated as an unknown viewpoint—not as a front image. Multiple useful views improve reconstruction accuracy.', label: 'Object image', allowMulti: true },
  human: { eyebrow: '3D HUMAN INPUT', title: 'Upload a realistic human photo', body: 'Use a face, portrait, or full-body photo from any reasonable angle. One photo has limited information; additional views can improve 3D reconstruction.', label: 'Human image', allowMulti: true },
  character: { eyebrow: '3D CHARACTER INPUT', title: 'Upload a photo for stylized character creation', body: 'Choose Cartoon, Anime, Stylized, or 3D animated character. Multiple views can improve reconstruction accuracy.', label: 'Character image', allowMulti: true },
}
const VIEW_LABELS = ['Unknown / Auto-detect view', 'Front', 'Back', 'Left', 'Right', 'Top', 'Bottom']
function sameFile(a, b) { return a && b && a.name === b.name && a.size === b.size && a.lastModified === b.lastModified }
function imageDimensions(url) { return new Promise(resolve => { const image = new window.Image(); image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight }); image.onerror = () => resolve({ width: 0, height: 0 }); image.src = url }) }
function describe(error) { if (error?.name === 'AbortError' || error?.name === 'TimeoutError') return 'Upload timed out. Confirm FastAPI is running on port 8000, then retry.'; if (error instanceof TypeError) return 'Backend is offline or the frontend proxy cannot reach port 8000.'; return error?.message || 'Upload failed for an unknown reason.' }

export default function UploadPanel({ mode, inputType, onInputTypeChange, characterStyle, onCharacterStyleChange, characterQuality, onCharacterQualityChange, onUploaded, onClear, uploadedFile, inputAnalysis, onInputAnalysis, inputViews = {}, onInputViewsChange }) {
  const inputRef = useRef(null); const extraRefs = useRef({}); const [dragOver, setDragOver] = useState(false); const [loading, setLoading] = useState(false); const [viewLoading, setViewLoading] = useState(''); const [error, setError] = useState(null)
  const copy = MODE_COPY[mode] || MODE_COPY.object; const multi = copy.allowMulti && inputType === 'multi_view'; const extras = useMemo(() => Object.entries(inputViews).filter(([key]) => key !== 'single'), [inputViews])
  function validate(file) { if (!file) return 'Choose an image first.'; if (!/\.(jpe?g|png)$/i.test(file.name) || (file.type && !ALLOWED.includes(file.type))) return 'Only JPG and PNG images are supported.'; if (file.size > MAX_MB * 1024 * 1024) return `Image is larger than the ${MAX_MB} MB limit.`; return null }
  async function upload(file, metadata = {}) { const validation = validate(file); if (validation) throw new Error(validation); const form = new FormData(); form.append('file', file); form.append('reconstruction_type', mode); form.append('input_type', inputType); form.append('view_label', metadata.viewLabel || 'Unknown / Auto-detect view'); const response = await fetch('/api/upload', { method: 'POST', body: form, signal: AbortSignal.timeout(30000) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || data.error || `Upload failed with HTTP ${response.status}.`); const localUrl = URL.createObjectURL(file); const dims = await imageDimensions(localUrl); return { filename: data.filename, size: data.size_bytes ?? file.size, width: data.width || dims.width, height: data.height || dims.height, localUrl, remoteUrl: data.url || `/uploads/${mode}/${data.stored_filename}`, fileId: data.file_id, sourceFile: file, inputType, reconstructionType: data.reconstruction_type, viewLabel: metadata.viewLabel || 'Unknown / Auto-detect view' } }
  async function selectSingle(file) { if (!file) return; setError(null); setLoading(true); try { const result = await upload(file); onUploaded(result.fileId, result); const analysis = await fetch(`/api/process/${result.fileId}/input-analysis?reconstruction_type=${encodeURIComponent(mode)}`); if (analysis.ok) onInputAnalysis?.(await analysis.json()) } catch (uploadError) { setError(describe(uploadError)) } finally { setLoading(false) } }
  async function addView(file) { if (!file) return; if (sameFile(file, uploadedFile?.sourceFile) || extras.some(([, view]) => sameFile(file, view.sourceFile))) { setError('That image is already in this project. Choose a different angle.'); return }; const key = `view-${Date.now()}`; setViewLoading(key); setError(null); try { const result = await upload(file); onInputViewsChange({ ...inputViews, [key]: result }) } catch (uploadError) { setError(describe(uploadError)) } finally { setViewLoading('') } }
  function removeView(key) { const next = { ...inputViews }; delete next[key]; onInputViewsChange(next) }
  async function replaceView(key, file) { if (!file) return; const otherViews = extras.filter(([viewKey]) => viewKey !== key); if (sameFile(file, uploadedFile?.sourceFile) || otherViews.some(([, view]) => sameFile(file, view.sourceFile))) { setError('That image is already in this project. Choose a different angle.'); return }; setViewLoading(key); setError(null); try { const result = await upload(file, { viewLabel: inputViews[key]?.viewLabel }); onInputViewsChange({ ...inputViews, [key]: result }) } catch (uploadError) { setError(describe(uploadError)) } finally { setViewLoading('') } }
  function updateViewLabel(key, viewLabel) { onInputViewsChange({ ...inputViews, [key]: { ...inputViews[key], viewLabel } }) }
  function reorder(key, direction) { const entries = Object.entries(inputViews); const movable = entries.filter(([current]) => current !== 'single'); const index = movable.findIndex(([current]) => current === key); const nextIndex = index + direction; if (index < 0 || nextIndex < 0 || nextIndex >= movable.length) return; [movable[index], movable[nextIndex]] = [movable[nextIndex], movable[index]]; const next = inputViews.single ? { single: inputViews.single } : {}; movable.forEach(([viewKey, view]) => { next[viewKey] = view }); onInputViewsChange(next) }
  function onDrop(event) { event.preventDefault(); setDragOver(false); selectSingle(event.dataTransfer?.files?.[0]) }
  return <div className="upload-workspace dedicated-input-workflow">
    <section className="card-panel input-guidance"><div><p className="eyebrow">{copy.eyebrow}</p><h3>{copy.title}</h3><p>{copy.body}</p></div>{multi && <div className="single-view-warning"><View size={19} /><span>Multiple views improve reconstruction accuracy. Label a view only when you know its angle; otherwise leave it on auto-detect.</span></div>}</section>
    {copy.allowMulti && <section className="input-type-card"><strong>Choose input setup</strong><div><button className={inputType === 'single' ? 'selected' : ''} onClick={() => onInputTypeChange('single')}><b>Single Image</b><small>One unknown camera viewpoint</small></button><button className={inputType === 'multi_view' ? 'selected' : ''} onClick={() => onInputTypeChange('multi_view')}><b>Multi-View</b><small>Two or more useful angles</small></button></div></section>}
    {mode === 'character' && <><section className="character-style-card"><strong>Character direction</strong><div>{['Realistic', 'Stylized', 'Cartoon', 'Anime', 'Chibi'].map(style => <button key={style} className={characterStyle === style ? 'selected' : ''} onClick={() => onCharacterStyleChange(style)}>{style}</button>)}</div><p>Style records the intended presentation. The evidence-based mesh remains derived from Depth Anything depth and the isolated photographed person—not invented anatomy.</p></section><section className="character-style-card"><strong>Mesh quality</strong><div>{['Draft', 'Standard', 'High Quality'].map(quality => <button key={quality} className={characterQuality === quality ? 'selected' : ''} onClick={() => onCharacterQualityChange(quality)}><b>{quality}</b>{quality === 'High Quality' && <small>Higher-density depth mesh; may take longer.</small>}</button>)}</div><p>Higher quality uses a denser person-only mesh and stronger edge-preserving depth refinement.</p></section></>}
    <div className={`drop-zone ${dragOver ? 'drag-over' : ''}`} onDragOver={event => { event.preventDefault(); setDragOver(true) }} onDragLeave={() => setDragOver(false)} onDrop={onDrop} onClick={() => !loading && inputRef.current?.click()}><input ref={inputRef} type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" hidden onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; selectSingle(file) }} />{loading ? <div className="spinner-wrap"><div className="spinner" /><span>Validating and uploading…</span></div> : <><UploadCloud size={52} className="dz-icon" /><h3>{uploadedFile ? `Replace ${copy.label.toLowerCase()}` : `Drop a ${copy.label.toLowerCase()} here`}</h3><p>JPG / PNG · maximum {MAX_MB} MB · preserved original</p><button className="btn btn-primary" style={{ pointerEvents: 'none' }}>Select image</button></>}</div>
    {error && <div className="state-box error"><AlertCircle size={32} /><h3>Upload could not continue</h3><p>{error}</p></div>}
    {uploadedFile && <section className="card-panel"><div className="card-title"><h3><CheckCircle size={18} /> Single image loaded</h3><span className="title-badge">UNKNOWN VIEWPOINT</span></div><div className="img-compare"><div className="img-panel"><label>{copy.label} · unknown / auto-detect view</label><img src={uploadedFile.localUrl} alt="Uploaded reconstruction input" /></div><div className="meta-list"><div className="meta-row"><span className="meta-label">File</span><span className="meta-value highlight">{uploadedFile.filename}</span></div><div className="meta-row"><span className="meta-label">Dimensions</span><span className="meta-value">{uploadedFile.width} × {uploadedFile.height}px</span></div><div className="meta-row"><span className="meta-label">Input type</span><span className="meta-value">{multi ? 'Multi-view set' : 'Single image'}</span></div>{inputAnalysis && <div className="analysis-note"><strong>Input guidance</strong><span>{inputAnalysis.workflow_recommendation}</span><small>{inputAnalysis.scene_classification_note}</small></div>}<p className="details-copy">Uploading does not add this item to history. Save it only after you choose to keep a generated project.</p><button className="btn btn-secondary clear-workspace-button" onClick={onClear}><Trash2 size={15} /> Clear {copy.label}</button></div></div></section>}
    {multi && <section className="card-panel multiview-panel"><div className="card-title"><h3>Additional views</h3><span className="title-badge">{(uploadedFile ? 1 : 0) + extras.length} / 2 MINIMUM</span></div><p className="details-copy">Add at least one more useful angle for multi-view input. Unknown / Auto-detect view is valid when you do not know the camera direction.</p><div className="view-grid">{extras.map(([key, view], index) => <div className="view-card detailed-view-card" key={key}><img src={view.localUrl} alt={`Additional view ${index + 1}`} /><strong>View {index + 2}</strong><select value={view.viewLabel || VIEW_LABELS[0]} onChange={event => updateViewLabel(key, event.target.value)}>{VIEW_LABELS.map(label => <option key={label}>{label}</option>)}</select><div className="view-card-actions"><button onClick={() => reorder(key, -1)} disabled={index === 0} aria-label="Move view earlier"><ArrowUp size={14} /></button><button onClick={() => reorder(key, 1)} disabled={index === extras.length - 1} aria-label="Move view later"><ArrowDown size={14} /></button><input ref={element => { extraRefs.current[key] = element }} type="file" accept="image/jpeg,image/png" hidden onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; replaceView(key, file) }} /><button onClick={() => extraRefs.current[key]?.click()} aria-label="Replace view"><Replace size={14} /></button><button onClick={() => removeView(key)} aria-label="Remove view"><Trash2 size={14} /></button></div></div>)}<div className="view-card add-view-card"><input ref={element => { extraRefs.current.new = element }} type="file" accept="image/jpeg,image/png" hidden onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; addView(file) }} /><button className="view-add" onClick={() => extraRefs.current.new?.click()} disabled={Boolean(viewLoading)}>{viewLoading ? <div className="spinner tiny" /> : <Plus size={18} />}<span>Add another view</span></button></div></div>{uploadedFile && extras.length < 1 && <div className="single-view-warning request-more"><View size={18} /><span>This project has areas that cannot be reconstructed reliably from one view. Add another angle for a better result.</span></div>}</section>}
  </div>
}
