import { useEffect, useState } from 'react'
import { Activity, BarChart2, Box, CircleHelp, Crosshair, History, Home, Image, Info, Layers, Mail, Map, Palette, PersonStanding, Play, Settings, Type } from 'lucide-react'
import UploadPanel from './components/UploadPanel'
import DepthPanel from './components/DepthPanel'
import CalibrationPanel from './components/CalibrationPanel'
import TerrainViewer from './components/TerrainViewer'
import FlythroughPanel from './components/FlythroughPanel'
import AnalyticsPanel from './components/AnalyticsPanel'
import AuthDialog from './components/AuthDialog'
import ObjectViewer from './components/ObjectViewer'
import AppearanceDialog from './components/AppearanceDialog'
import TextTo3DPanel from './components/TextTo3DPanel'
import QueryPanel from './components/QueryPanel'
import HomeDashboard from './components/HomeDashboard'
import AboutPage from './components/AboutPage'
import ContactPage from './components/ContactPage'
import HelpCenter from './components/HelpCenter'
import './App.css'

const MODES = [{ key: 'object', label: '3D Object', icon: Box, description: 'Products and physical objects' }, { key: 'terrain', label: '3D Terrain', icon: Map, description: 'Maps and landscapes' }, { key: 'human', label: '3D Human', icon: PersonStanding, description: 'Realistic human reconstruction' }, { key: 'character', label: '3D Character', icon: PersonStanding, description: 'Anime, cartoon, and stylized characters' }, { key: 'text', label: 'Text to 3D', icon: Type, description: 'Local 3D typography' }]
const IMAGE_MODES = ['object', 'terrain', 'human', 'character']
const TERRAIN_MENU = [{ key: 'input', label: 'Terrain Input', icon: Image }, { key: 'depth', label: 'Depth Analysis', icon: Layers }, { key: 'calibration', label: 'Elevation Calibration', icon: Settings }, { key: 'terrain', label: '3D Terrain', icon: Box }, { key: 'flythrough', label: 'Flythrough', icon: Play }, { key: 'query', label: 'Point Query', icon: Crosshair }, { key: 'analytics', label: 'Analytics', icon: BarChart2 }]
const RECONSTRUCTION_MENU = [{ key: 'input', label: 'Input Setup', icon: Image }, { key: 'depth', label: 'Depth Analysis', icon: Layers }, { key: 'object', label: '3D Reconstruction', icon: Box }, { key: 'flythrough', label: 'Flythrough', icon: Play }, { key: 'analytics', label: 'Analytics', icon: BarChart2 }]
const TITLES = { home: '2D → 3D AI Reconstruction Studio', help: 'Help Center', about: 'About 3D DepthVision', contact: 'Contact 3D DepthVision', input: 'Input Setup', depth: 'Depth Analysis', calibration: 'Elevation Calibration', terrain: '3D Terrain Viewer', flythrough: '3D Flythrough', query: 'Point Query', analytics: 'Project Analytics', object: '3D Reconstruction', text: '3D Typography Studio' }
const emptyWorkspace = () => ({ fileId: null, uploadedFile: null, depthResult: null, calibResult: null, terrainData: null, objectData: null, analyticsData: null, inputAnalysis: null, inputViews: {}, inputType: 'single', characterStyle: 'Stylized', characterQuality: 'Standard' })
const initialWorkspaces = () => Object.fromEntries(IMAGE_MODES.map(mode => [mode, emptyWorkspace()]))
function readHistory(email) { try { return email ? JSON.parse(localStorage.getItem(`depthvision-history:${email}`)) || [] : [] } catch { return [] } }
function modeLabel(mode) { return MODES.find(item => item.key === mode)?.label || '3D Reconstruction' }

export default function App() {
  const [activeTab, setActiveTab] = useState(() => window.location.hash === '#contact' ? 'contact' : window.location.hash === '#about' ? 'about' : 'home'); const [reconstructionMode, setReconstructionMode] = useState('terrain'); const [workspaces, setWorkspaces] = useState(initialWorkspaces)
  const [backendOk, setBackendOk] = useState(null); const [backendInfo, setBackendInfo] = useState(null); const [profile, setProfile] = useState(() => { try { return JSON.parse(localStorage.getItem('depthvision-profile')) } catch { return null } }); const [showAuth, setShowAuth] = useState(false); const [authPurpose, setAuthPurpose] = useState('general'); const [showHistory, setShowHistory] = useState(false); const [showAppearance, setShowAppearance] = useState(false); const [history, setHistory] = useState(() => readHistory(profile?.email)); const [theme, setTheme] = useState(() => localStorage.getItem('depthvision-theme') || 'midnight')
  const workspace = workspaces[reconstructionMode] || emptyWorkspace()
  const updateWorkspace = (mode, patch) => setWorkspaces(current => ({ ...current, [mode]: { ...current[mode], ...patch } }))
  useEffect(() => { localStorage.setItem('depthvision-theme', theme) }, [theme])
  useEffect(() => { const onHashChange = () => setActiveTab(window.location.hash === '#contact' ? 'contact' : window.location.hash === '#about' ? 'about' : 'home'); window.addEventListener('hashchange', onHashChange); return () => window.removeEventListener('hashchange', onHashChange) }, [])
  useEffect(() => { const controller = new AbortController(); fetch('/api/health', { signal: controller.signal }).then(async response => { if (!response.ok) throw new Error('Health check failed'); return response.json() }).then(data => { setBackendOk(true); setBackendInfo(data) }).catch(error => { if (error.name !== 'AbortError') setBackendOk(false) }); return () => controller.abort() }, [])
  function saveProfile(next) { localStorage.setItem('depthvision-profile', JSON.stringify(next)); setProfile(next); setHistory(readHistory(next.email)); setShowAuth(false) }
  function signOut() { localStorage.removeItem('depthvision-profile'); setProfile(null); setHistory([]); setShowHistory(false) }
  function saveProjectToHistory(mode = reconstructionMode, metadata = {}) { const active = workspaces[mode]; if (!profile?.email || !active?.uploadedFile?.fileId) return; const key = `depthvision-history:${profile.email}`; if (history.some(item => item.fileId === active.fileId && item.type === mode)) return; const entry = { id: crypto.randomUUID(), fileId: active.fileId, type: mode, filename: active.uploadedFile.filename, width: active.uploadedFile.width, height: active.uploadedFile.height, inputType: active.inputType, inputViewCount: Object.keys(active.inputViews).length || 1, createdAt: new Date().toISOString(), ...metadata }; const next = [entry, ...history].slice(0, 30); localStorage.setItem(key, JSON.stringify(next)); setHistory(next) }
  function saveTypographyToHistory(project) { if (!profile?.email || !project?.text?.trim()) return; const key = `depthvision-history:${profile.email}`; const entry = { id: crypto.randomUUID(), type: 'text', filename: project.text.trim(), text: project.text.trim(), style: `${project.fontStyle} · ${project.meshStyle}`, material: project.material, status: project.status || 'Local mesh ready', createdAt: new Date().toISOString() }; const next = [entry, ...history].slice(0, 30); localStorage.setItem(key, JSON.stringify(next)); setHistory(next) }
  function chooseMode(mode) { setReconstructionMode(mode); setActiveTab(mode === 'text' ? 'text' : 'input') }
  function resetForNewImage(mode, id, info) { updateWorkspace(mode, { fileId: id, uploadedFile: info, depthResult: null, calibResult: null, terrainData: null, objectData: null, analyticsData: null, inputAnalysis: null, inputViews: { single: info } }) }
  function openHistoryItem(item) { const mode = MODES.some(entry => entry.key === item.type) ? item.type : 'object'; chooseMode(mode); setShowHistory(false) }
  function renameHistory(id) { const current = history.find(item => item.id === id); const name = window.prompt('Rename saved project', current?.text || current?.filename || ''); if (!name?.trim()) return; const next = history.map(item => item.id === id ? { ...item, filename: name.trim(), text: item.text ? name.trim() : undefined } : item); localStorage.setItem(`depthvision-history:${profile.email}`, JSON.stringify(next)); setHistory(next) }
  function deleteHistory(id) { const next = history.filter(item => item.id !== id); localStorage.setItem(`depthvision-history:${profile.email}`, JSON.stringify(next)); setHistory(next) }
  const isText = reconstructionMode === 'text'; const menu = reconstructionMode === 'terrain' ? TERRAIN_MENU : RECONSTRUCTION_MENU; const title = activeTab === 'object' ? `${modeLabel(reconstructionMode)} Viewer` : TITLES[activeTab]
  return <div className="dashboard-container" data-theme={theme}>
    <aside className="sidebar compact-sidebar">
      <button className="sidebar-logo icon-rail-item" data-label="3D DepthVision" onClick={() => setActiveTab('home')} aria-label="3D DepthVision home">
        <img className="brand-logo-image" src="/depthvision-logo.png" alt="3D DepthVision" /><span className="brand-name">3D DepthVision</span>
      </button>
      <button className={`home-nav icon-rail-item ${activeTab === 'home' ? 'active' : ''}`} data-label="Home" onClick={() => setActiveTab('home')} aria-label="Home"><Home size={18} /><span>Home</span></button>
      <div className="mode-picker">{MODES.map(({ key, label, icon: Icon, description }) => <button key={key} className={reconstructionMode === key && activeTab !== 'home' ? 'selected' : ''} data-label={label} onClick={() => chooseMode(key)} title={description} aria-label={label}><Icon size={18} /><span>{label}</span></button>)}</div>
      {activeTab !== 'home' && !isText && <ul className="sidebar-menu">{menu.map(({ key, label, icon: Icon }) => <li key={key} className={`menu-item icon-rail-item ${activeTab === key ? 'active' : ''}`} data-label={label} onClick={() => setActiveTab(key)}><Icon size={18} /><span>{label}</span></li>)}</ul>}
      <div className="sidebar-utility">
        <button className="sidebar-history-button icon-rail-item" data-label="History" onClick={() => profile ? setShowHistory(true) : (setAuthPurpose('history'), setShowAuth(true))} aria-label="History"><History size={18} /><span>History</span></button>
        <button className="sidebar-link icon-rail-item" data-label="Help Center" onClick={() => setActiveTab('help')} aria-label="Help Center"><CircleHelp size={18} /><span>Help Center</span></button>
        <button className="sidebar-link icon-rail-item" data-label="About Us" onClick={() => setActiveTab('about')} aria-label="About Us"><Info size={18} /><span>About Us</span></button>
        <button className="sidebar-link icon-rail-item" data-label="Contact" onClick={() => setActiveTab('contact')} aria-label="Contact"><Mail size={18} /><span>Contact</span></button>
      </div>
    </aside>
    <div className="main-workspace"><header className="main-header"><div className="header-title"><p className="header-mode">{activeTab === 'home' ? 'WELCOME' : modeLabel(reconstructionMode)}</p><h2>{title}</h2></div><div className="header-status"><div className="connection-badge"><span className={`badge-dot ${backendOk ? 'connected' : ''}`} />{backendOk === null ? 'Connecting…' : backendOk ? 'Backend Online' : 'Backend Offline'}</div>{backendInfo?.hardware && <div className="connection-badge"><Activity size={13} />{backendInfo.hardware.gpu_available ? `GPU: ${backendInfo.hardware.gpu_name}` : 'Automatic compute'}</div>}<button className="header-action" onClick={() => setShowAppearance(true)}><Palette size={14} /> Appearance</button>{profile ? <button className="header-action profile-action" onClick={signOut}>{profile.name}</button> : <button className="header-action primary-action" onClick={() => { setAuthPurpose('general'); setShowAuth(true) }}>Sign in</button>}</div></header><main className="content-area">
      {activeTab === 'home' && <HomeDashboard onChoose={chooseMode} />}
      {activeTab === 'help' && <HelpCenter onContact={() => setActiveTab('contact')} />}
      {activeTab === 'about' && <AboutPage />}
      {activeTab === 'contact' && <ContactPage />}
      {activeTab === 'input' && <UploadPanel mode={reconstructionMode} inputType={workspace.inputType} onInputTypeChange={value => updateWorkspace(reconstructionMode, { inputType: value })} characterStyle={workspace.characterStyle} onCharacterStyleChange={value => updateWorkspace('character', { characterStyle: value })} characterQuality={workspace.characterQuality} onCharacterQualityChange={value => updateWorkspace('character', { characterQuality: value })} onUploaded={(id, info) => resetForNewImage(reconstructionMode, id, info)} onClear={() => updateWorkspace(reconstructionMode, emptyWorkspace())} uploadedFile={workspace.uploadedFile} inputAnalysis={workspace.inputAnalysis} onInputAnalysis={value => updateWorkspace(reconstructionMode, { inputAnalysis: value })} inputViews={workspace.inputViews} onInputViewsChange={value => updateWorkspace(reconstructionMode, { inputViews: value })} />}
      {activeTab === 'depth' && <DepthPanel fileId={workspace.fileId} uploadedFile={workspace.uploadedFile} depthResult={workspace.depthResult} mode={reconstructionMode} inputViewCount={Object.keys(workspace.inputViews).length || 1} onDepthDone={value => updateWorkspace(reconstructionMode, { depthResult: value, terrainData: null, objectData: null })} />}
      {activeTab === 'calibration' && <CalibrationPanel fileId={workspace.fileId} uploadedFile={workspace.uploadedFile} depthResult={workspace.depthResult} calibResult={workspace.calibResult} onCalibDone={value => updateWorkspace('terrain', { calibResult: value, terrainData: null })} />}
      {activeTab === 'terrain' && <TerrainViewer fileId={workspace.fileId} depthResult={workspace.depthResult} terrainData={workspace.terrainData} onTerrainLoaded={value => updateWorkspace('terrain', { terrainData: value })} onPointClick={(x, y) => updateWorkspace('terrain', { analyticsData: { x: Math.round(x), y: Math.round(y), fileId: workspace.fileId } })} onSave={() => saveProjectToHistory('terrain')} canSave={Boolean(profile)} />}
      {activeTab === 'flythrough' && <FlythroughPanel fileId={workspace.fileId} depthResult={workspace.depthResult} terrainData={workspace.terrainData} mode={reconstructionMode} onTerrainLoaded={value => updateWorkspace(reconstructionMode, { terrainData: value })} onExit={() => setActiveTab(reconstructionMode === 'terrain' ? 'terrain' : 'object')} />}
      {activeTab === 'query' && <QueryPanel fileId={workspace.fileId} uploadedFile={workspace.uploadedFile} initialPoint={workspace.analyticsData} />}
      {activeTab === 'object' && <ObjectViewer fileId={workspace.fileId} uploadedFile={workspace.uploadedFile} depthResult={workspace.depthResult} objectData={workspace.objectData} mode={reconstructionMode} inputViews={workspace.inputViews} characterStyle={workspace.characterStyle} characterQuality={workspace.characterQuality} onObjectLoaded={value => updateWorkspace(reconstructionMode, { objectData: value })} onSave={() => saveProjectToHistory(reconstructionMode, { characterStyle: workspace.characterStyle, characterQuality: workspace.characterQuality })} canSave={Boolean(profile)} />}
      {activeTab === 'text' && <TextTo3DPanel onSaveProject={saveTypographyToHistory} canSave={Boolean(profile)} />}
      {activeTab === 'analytics' && <AnalyticsPanel fileId={workspace.fileId} uploadedFile={workspace.uploadedFile} objectData={workspace.objectData} terrainData={workspace.terrainData} depthResult={workspace.depthResult} inputAnalysis={workspace.inputAnalysis} history={history} reconstructionMode={reconstructionMode} inputType={workspace.inputType} inputViewCount={Object.keys(workspace.inputViews).length || 1} onSave={() => saveProjectToHistory(reconstructionMode)} canSave={Boolean(profile)} />}
    </main></div>
    <AuthDialog open={showAuth} purpose={authPurpose} onClose={() => setShowAuth(false)} onSave={saveProfile} /><AppearanceDialog open={showAppearance} theme={theme} onSelect={setTheme} onClose={() => setShowAppearance(false)} />
    {showHistory && <div className="modal-backdrop" onMouseDown={() => setShowHistory(false)}><section className="auth-dialog history-dialog" onMouseDown={event => event.stopPropagation()}><button className="modal-close" onClick={() => setShowHistory(false)}>×</button><p className="eyebrow">SAVED PROJECT HISTORY</p><h3>Saved projects</h3>{history.length ? <div className="history-list">{history.map(item => <div className="history-item" key={item.id}><div><strong>{item.text || item.filename}</strong><span>{modeLabel(item.type)} · {item.status || 'Saved'} · {new Date(item.createdAt).toLocaleString()}</span></div><aside><button onClick={() => openHistoryItem(item)}>View</button><button onClick={() => renameHistory(item.id)}>Rename</button><button className="danger" onClick={() => deleteHistory(item.id)}>Delete</button></aside></div>)}</div> : <p className="dialog-copy">Save a generated model or project to add it here. Uploading never saves it automatically.</p>}</section></div>}
  </div>
}
